In [1]:
from neuralnet import NeuralNet, crossentropy
from activations import sigmoid, relu, softmax

import numpy as np

In [22]:
Z = [[0.3394572666491664, 0.3089068053925853, 0.3516359279582483], [0.33932706934615525, 0.3094755563319447, 0.3511973743219001], [0.3394407172182317, 0.30889042266755573, 0.35166886011421256], [0.3394407172182317, 0.30889042266755573, 0.35166886011421256]]

In [30]:
forward, backward = softmax()
A, Z = forward(Z)
print(A)

[[0.25001021 0.2499665  0.25002329]
 [0.24997766 0.2501087  0.24991366]
 [0.25000607 0.2499624  0.25003152]
 [0.25000607 0.2499624  0.25003152]]


In [31]:
dZ = backward(0, Z)
print(dZ)

None
